### ISSUE TITLE
YABBA barrels invisible

### ISSUE THREAD

**Issue by redawgts** [CyanideX/Unity#185]
Item barrels and Decorative blocks from the YABBA mod are invisible. No sure if it's a mod problem or a problem with Unity.
![2019-03-06_08 11 14](https://user-images.githubusercontent.com/6427199/53883690-ad5c1880-3fe7-11e9-882f-000830652d70.png)

**Comment by jbcraft6** [comment]
I've seen this as well.

**Comment by Dimentive** [comment]
To see if it’s a problem with Unity, simply disable the resource pack.

**Comment by Dimentive** [comment]
To check if it’s a problem with Unity, simply disable the resource pack.

**Comment by CyanideX** [comment]
It is most likely Unity. Does this happen when applying the pack in-game or does it look like this after a fresh launch of the game with the resource pack already applied?

**Comment by cosmodd** [comment]
I have the same problem, from what I've seen, they are and will remain invisible in any case. I would really like to know how to solve this problem :l
(By any case, I mean fresh launch, pack already applied and when applying it)

**Comment by CyanideX** [comment]
It's odd because we don't support YABBA so there shouldn't be any assets altering the mod.

**Comment by SheroxGG** [comment]
I am still having this problem, any way to fix it? Ty!

**Comment by chazwarp923** [comment]
I just did a ton of testing, and the only solution that actually fixed the issue, was removing any textures that had ctm. I'd say it's an incompatibility between yabba and ctm. Tested with literally just yabba, ftblib and ctm. Nothing else.

**Comment by murilorodelli** [comment]
This is happening to me as well

**Comment by CyanideX** [comment]
@ChloeDawn do you know why this is still happening? I can't seem to figure out the cause; we don't even have textures for Yabba.

**Comment by murilorodelli** [comment]
It is still happening. And I'm sure it is Unity textures that cause it. I've tried with and without optifine with same results. The same as the picture on top. I'm using 1.12 version

**Comment by CyanideX** [comment]
![Image](https://i.imgur.com/wTXrMAv.png)

This is with the latest Unity for 1.12 from CurseForge and YABBA installed. There is no issue with Unity that I can see.

Seems like it might be another mod interaction or perhaps OptiFine settings?

**Comment by tterrag1098** [comment]
Just for the record, a problem going away when something is uninstalled does NOT mean that the fault lies with that thing. There are so many interactions going on, you simply cannot draw that conclusion. First step to solving a problem like this is to reduce variables, which means installing ONLY Unity and YABBA, which @CyanideX has done for you above. This tells us that the problem is triggered by something else entirely.

Not to mention that Unity is a resource pack that has no textures for YABBA and so cannot be the cause of this bug, it is the job of mod developers to be compatible with resource packs (unless the resource pack is specifically messing up their models/textures, which is not the case here).

**Comment by CyanideX** [comment]
I've released a workaround:

https://www.curseforge.com/minecraft/texture-packs/unity/files/2805035
