### ISSUE TITLE
Bug with Tree Leaves in distance

### ISSUE THREAD

**Issue by RexOrbis** [CyanideX/Unity#199]
I have been having a problem with tree leaves on the 1.12.2 version of Unity. There is a border some distance away from the player where closer leaves are darker and the leaves beyond are slightly lighter in colour. This bug is not visible from my testing with the vanilla resource pack.
I am playing with fancy settings and mipmap 4, and changing these values doesn't seem to change this border in any way. I am not playing with any visual mods or other resource packs.

https://imgur.com/a/GKHazru

Thank you very much.

**Comment by CyanideX** [comment]
There's nothing I can do about that, sadly. It's just how the texture tiles at distance from that angle and no amount of anisotropic filtering can fix it. I would have to remake the texture specifically for that issue. 😓

I may revisit this issue later but, at the moment, it's not my top priority. Thanks for bringing it up though!

**Comment by RexOrbis** [comment]
So, which textures can I delete to make this problem go away? Just delete all the leaf textures and it'll be fine?

**Comment by CyanideX** [comment]
Yes, deleting the leaves textures would solve the issue if it's really bothering you that much. An alternate option would be to use OptiFine and use it's anisotropic filtering options. 

![OptiFine](https://i.imgur.com/L3rK7pj.png)


It also seems that the newest Unity jungle leaves may not have this issue. The image below was also taken in version 1.15 so that could be another reason why the issue isn't present. Perhaps you could replace the old leaves with the new ones.

![2020-03-29_17 25 21](https://user-images.githubusercontent.com/3106700/77865267-57ee3d00-71e2-11ea-93e2-24952a3e25c4.png)

**Comment by RexOrbis** [comment]
I used optifine and turned anisotropic filtering up to trilinear but it didn't fix the problem. I will try using the 1.15 textures.

Edit: in Unity 1.15, there is both a "minecraft" and "unity" folder, which both contain leaf textures. Which do I use?

**Comment by CyanideX** [comment]
You need to change the anisotropic filtering slider (max of 16x), not just the method of AF. 

![image](https://user-images.githubusercontent.com/3106700/77870228-bc66c780-71f5-11ea-8dde-fba20439e29b.png)

Don't go too extreme though. It doesn't always look good. 😝 

![image](https://user-images.githubusercontent.com/3106700/77870303-e15b3a80-71f5-11ea-8764-8986539ebba7.png)

To answer your question, you can take the leaves from the minecraft folder; the unity folder contains the variants.

**Comment by CyanideX** [comment]
Quick update: this is what mine looks like with OptiFine installed, 'Mipmap Levels' off, 'Mipmap Type' set to nearest, and 'Anisotropic Filtering' off.

![image](https://user-images.githubusercontent.com/3106700/77870541-8a099a00-71f6-11ea-9c49-21339b39fb41.png)

**Comment by RexOrbis** [comment]
Thank you so much, that improves everything.
