### ISSUE TITLE
[1.16.1]Textures are vanilla in some cases

### ISSUE THREAD

**Issue by iam-cult** [CyanideX/Unity#214]
**Describe the Issue**
variants of coal, as well as stone textures, include vanilla base textures, in addition, stone that is places takes on a vanilla texture. This could be intentional, but I'm reporting here anyways

**To Reproduce**
1. Load up minecraft 1.16.1 with unity 2.3.1
2. Go to a mountains biome
3. look at the various clusters of coal, and at the stone textures
4. 

**Expected Behavior**
Most of the stone has the vanilla texture, and some of the coal does too
**Screenshots**
![2020-07-22_10 31 41](https://user-images.githubusercontent.com/65368815/88189817-7b148080-cc07-11ea-854b-9ddc46215650.png)
![2020-07-22_10 32 50](https://user-images.githubusercontent.com/65368815/88189845-84055200-cc07-11ea-95cc-fb5cd0b05ada.png)

**Additional Context**
resource packs used: Unity base, unity modded, unity dark edition
mods used: Optifine, Quark, Abnormals core, Buzzier bees, Autoreglib, ironchest, jei, Enhanced mushrooms, Mekanism, Mekanism additions, Mekanism Generators, Mekanism tools, metal barrels, the one probe, Waystones, toolbelt

**Comment by CyanideX** [comment]
That is very much intentional. Those are variants the same blocks which are designed to look different and avoid obvious tiling patterns.

![image](https://user-images.githubusercontent.com/3106700/88201288-1ef82f00-cbfc-11ea-91d9-75586b50ca5c.png)

The above screenshot shows vanilla dirt (1 texture with random rotations) while the one below is Unity dirt with variants (8 textures with varying colors and contrast - some with rocks and debris). 

![image](https://user-images.githubusercontent.com/3106700/88201348-30d9d200-cbfc-11ea-92cc-4bb52117bb53.png)

Here are links to comparison gifs I posted a while ago:

https://twitter.com/theCyanideX/status/888127684705779713/photo/1

https://twitter.com/theCyanideX/status/1184328025678041088

https://twitter.com/theCyanideX/status/1184311730542804994


You can see how the variants remove most of the tiling effect. I do understand that the ore textures don't quite match in style so I will be revisiting those but the stone variants are intentional. Having stone variants is important in large, flat natural world generation. 🙂

**Comment by iam-cult** [comment]
I was wondering, the ores use the less vanilla stone variant as a background, but I get that the ore textures correspond to the stone ones

**Comment by iam-cult** [comment]
Thanks for the help

**Comment by CyanideX** [comment]
I will see about revisiting the ore textures to make sure they don't stick out too much; that wasn't my goal. Please let me know if you come across any other variants that are a bit jarring. 😀
