### ISSUE TITLE
Lever in Inverted State

### ISSUE THREAD

**Issue by axieum** [CyanideX/Unity#216]
**Describe the Issue**
The lever model is inverted when placed on a wall.

**To Reproduce**
Steps to reproduce the behaviour:
1. Place a 'Lever' vertically on a wall
2. Notice how the lever is in the down position initially
3. Click the 'Lever' and notice that it is now in the up position and is active

**Expected Behaviour**
A lever is un-powered in the up position, and powered in the down position.

**Screenshots**
Lever in un-powered state: 
![image](https://user-images.githubusercontent.com/7577851/89096119-67db8f00-d417-11ea-9f84-0e5cc58d9293.png)

Lever in powered state: 
![image](https://user-images.githubusercontent.com/7577851/89096130-77f36e80-d417-11ea-81e1-0b69888f1bde.png)

**Additional Context**
I have Unity Base (2.3.1), Unity Modded (1.2.0) and Unity Dark (0.6.2) active in-order respectively.

**Comment by CyanideX** [comment]
![image](https://user-images.githubusercontent.com/3106700/89096819-4b474480-d38e-11ea-9766-14b8dcc35b7b.png)

My goal was to make it more like a switch (or light switch) which uses the upward position to indicate 'on', unlike levers which are typically activated when pulling down. If you'd prefer to keep them the other way, the fix is very simple: head to the following directory and swap the names of these two models:

![image](https://user-images.githubusercontent.com/3106700/89096885-e17b6a80-d38e-11ea-98ec-992b7ff47558.png)

Hope this helps! 🙂

**Comment by axieum** [comment]
> unlike levers which are typically activated when pulling down

The item itself is called a "Lever", maybe you could consider renaming it to a "Switch" if that is even possible in a resource pack?

Thank you for taking the time to show how to make this change on our ends! ❤️

**Comment by CyanideX** [comment]
I don't like to change the names of blocks or items because it would make it difficult for people to search for them if they were not aware of the name change.
