### ISSUE TITLE
(Suggestion) Make emissive textures work in optifine

### ISSUE THREAD

**Issue by redstonek** [CyanideX/Unity#234]
**Suggestion**
Make emissive textures work in optifine without using connected textures mod.

**Comment by CyanideX** [comment]
Are you referring to [Unity: Extras](https://github.com/Unity-Resource-Pack/Unity-Extras) redstone or the base pack nether emissives?

I most likely won't be changing things since OptiFine only allows fullbright textures or nothing at all. I don't want redstone to be light level 15, for example, which is why I use CTM. For certain textures, sure, I'll use OptiFine for emissives.

**Comment by redstonek** [comment]
I meant emissives overall.

**Comment by CyanideX** [comment]
Emissives that are intended to be fullbright will use OptiFine format.
