### ISSUE TITLE
[1.16.5] Issue Description

### ISSUE THREAD

**Issue by Ghostigul** [CyanideX/Unity#236]
Vines look horrible 

Look at vines

![image](https://user-images.githubusercontent.com/81652252/113054454-0bc83680-916f-11eb-8943-6031800a23ef.png)

![image](https://user-images.githubusercontent.com/81652252/113054509-1d114300-916f-11eb-9706-744f1f9ab33a.png)

Using Optifine and SEUS renewed 1.0.1

**Comment by CyanideX** [comment]
You said this earlier:
![image](https://user-images.githubusercontent.com/3106700/113071041-cad51f80-9178-11eb-804d-05e8d383f5dc.png)

Yet you're using my Unity PBR pack that says "**_Designed for SEUS PTGI_**" alongside SEUS Renewed, getting issues related to **shaders** and making an issue report on the base Unity repo instead of the [Unity PBR repo](https://github.com/Unity-Resource-Pack/Unity-PBR). 

I also said in my reply to you: "Please submit an issue to the repo and follow the template" but you completely disregarded that and didn't even bother naming your issue:

![image](https://user-images.githubusercontent.com/3106700/113071307-4df67580-9179-11eb-8bd0-48fa115ea9ca.png)

So, to respond to this:
![image](https://user-images.githubusercontent.com/3106700/113071319-564eb080-9179-11eb-93b9-9df9d07de918.png)

No. I'm done being nice when people can't follow simple instructions.

**Comment by CyanideX** [comment]
I've closed the issue because this is an issue for Unity PBR but I will try to look into fixing this the next time I update PBR.

**Comment by Ghostigul** [comment]
Imagine being this much of an asshole

**Comment by CyanideX** [comment]
We don't have to imagine! 

![image](https://user-images.githubusercontent.com/3106700/113216383-1ea33f80-9231-11eb-8e7d-21850e4448d6.png)

**Comment by Ghostigul** [comment]
I do

**Comment by CyanideX** [comment]
Well let me help you.

Steps to not be on the receiving end of my assholery:

1. Don't be a dumbass.
2. Read instructions.
3. Understand instructions.
4. Post issues on the repo, not in a comment on CurseForge.
5. Don't post vague comments.
6. Post issues in the right repo.
7. Read project descriptions.
8. Learn how to make a useful issue report.
9. Don't be a dumbass.

And, in case I didn't say this before, thank you so much for your support. I am always happy to meet a fan of Unity and will do my best to continue to update the pack so that your experience is the best it can be!
