### ISSUE TITLE
Integrated Dynamics

### ISSUE THREAD

**Issue by rubensworks** [CyanideX/Unity#69]
I've been getting a lot of comments on the color scheme of [Integrated Dynamics](http://minecraft.curseforge.com/projects/integrated-dynamics).
Since I'm not really a good texture artist, I was thinking that people might like it if the mod got a texture remake from the Unity team.
I would be happy to use them as default textures if you're up for it ;-)

**Comment by Yulife** [comment]
Mhmhm, @elucent and I had a talk about retexturing ID actually yesterday :) Was thinking about a general gray scheme with those baby blue highlights so that the mod does not lose its original flavor. What do you think? Maybe go for a different tree color scheme too but I'll do something about that today maybe :)

**Comment by rubensworks** [comment]
That sounds awesome :)
The cyan highlights are indeed something I would like to see, since they are indicative for the Menril material which is used in all crafting recipes.

**Comment by Yulife** [comment]
Hey can you come on IRC or discord???
